SLI-904 Fix medium test after the update of SonarJS
Due to some changes in SonarJS, probbaly in the way the tsconfig.json file is generated,
the anlaysis is crashing when trying to analyze in memory files created by the testFixture.

For reference, here is the error in analysis logs:

```
Using generated tsconfig.json file using wildcards [/tmp/tmp-287843-9GvB9c7iSFlr]
Error: No inputs were found in config file '/tmp/tmp-287843-9GvB9c7iSFlr'. Specified 'include' paths were '["/tmp/unitTest_should_find_secrets_excluding_vcs_ignored_files_2P3cySPHEAkWGvdfs8ZMp77FSIm/**/*"]' and 'exclude' paths were '[]'.
    at createProgramOptions (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/lib/services/program/program.js:125:15)
    at default_1 (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/lib/routing/on-tsconfig-files.js:15:60)
    at Layer.handle [as handle_request] (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/layer.js:95:5)
    at /home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:346:12)
    at next (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/julien.henry/Projects/sonarlint/sonarlint-intellij/build/idea-sandbox/system-test/tmp/sonarlint/.sonarlinttmp_10234387009677536278/eslint-bridge-bundle/package/node_modules/express/lib/router/index.js:175:3)
No inputs were found in config file '/tmp/tmp-287843-9GvB9c7iSFlr'. Specified 'include' paths were '["/tmp/unitTest_should_find_secrets_excluding_vcs_ignored_files_2P3cySPHEAkWGvdfs8ZMp77FSIm/**/*"]' and 'exclude' paths were '[]'.
tsconfig /tmp/tmp-287843-9GvB9c7iSFlr files null
Could not normalize /src/src/devenv.js
/src/src/devenv.js matched NO_CONFIG
Could not normalize /src/src/devenv_unversionned.js
/src/src/devenv_unversionned.js matched NO_CONFIG
```